#!/bin/bash
# Copyright 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# We're in the tools directory.
THIS_DIR="$(dirname "$0")"
exec "$THIS_DIR/../tools/run_dart.sh" "${THIS_DIR}/vterm_test_filter.dart"
